from __future__ import annotations

from typing import Protocol

from backend.domain.entities import Description, Edge, Node, NodeId, Subgraph


class OntologyRepository(Protocol):
    def get_node(self, id: NodeId) -> Node: ...

    def get_edge(self, source: NodeId, target: NodeId, predicate: str) -> Edge: ...

    def parents_of(self, id: NodeId) -> list[Node]: ...

    def shortest_path(self, id: NodeId) -> list[Node]: ...

    def subgraph(self, root: NodeId, max_depth: int = 1) -> Subgraph: ...

    def all_nodes(self) -> list[Node]: ...

    def all_edges(self) -> list[Edge]: ...

    def add_node(self, node: Node) -> None: ...

    def remove_node(self, id: NodeId) -> None: ...

    def import_payload(self, payload: dict) -> None: ...

    def add_edge(self, edge: Edge) -> None: ...

    def remove_edge(self, source: NodeId, target: NodeId, predicate: str) -> None: ...

    def update_edge_descriptions(
        self,
        source: NodeId,
        target: NodeId,
        predicate: str,
        descriptions: tuple[Description, ...],
    ) -> None: ...

    def pending_edges(self) -> list[Edge]: ...

    def commit(self) -> None: ...


class LLMProvider(Protocol):
    name: str

    async def describe(self, label: str, code: str, parent_chain: list[str]) -> list[str]: ...
